<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Data\Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mo_Talabat_Application_Abstractions\Mo_Talabat_Core_Application_Abstractions.csproj" />
    <ProjectReference Include="..\Mo_Talabat_Core_Domain\Mo_Talabat_Core_Domain.csproj" />
  </ItemGroup>

</Project>
