<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mo_Talabat_Core_Domain\Mo_Talabat_Core_Domain.csproj" />
    <ProjectReference Include="..\Share\Share.csproj" />
  </ItemGroup>

</Project>
